### ISSUE TITLE
Link to "View the Silverstripe CMS pattern library" broken

### ISSUE THREAD

**Issue by callan-stretton** [silverstripe/silverstripe-pattern-lib#1]
Hi there, it looks like the link to view the [Silverstripe CMS pattern library](https://silverstripe.github.io/silverstripe-pattern-lib) is broken - 404

**Comment by brynwhyman** [comment]
Hi, @callan-stretton thanks for reporting this. We'll have a look at what's going wrong here. 

You should still be able to get it running locally following this guide: http://www.silverstrip.es/blog/getting-the-new-silverstripe-pattern-library-running/

**Comment by maxime-rainville** [comment]
The pattern lib should be back now. It's only a partial fix, I had to remove the session manager module to get it working.

I've also updated the build script to hard fail if the pattern library generation fails. That way 'll get a notification when it fails and it won't push an empty folder to GitHub pages.

**Comment by edwilde** [comment]
@GuySartorelli i'd think this can be closed now

**Comment by GuySartorelli** [comment]
Yup good catch, thanks
